name = "BatchedBLAS"
uuid = "dfa6e8bd-ffa5-4347-817a-aa08eb84b250"
authors = ["Ben Arthur <arthurb@hhmi.org>"]
version = "0.2.4"

[deps]
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
julia = "1.6"
